import Notification from "@/components/Notification";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Session from "@/components/authsession";
import { Quaryfun } from "@/components/Quarystack";
import Tenquary from "@/components/Quar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Tenquary>
          <Quaryfun>
          <Session>
          <Notification />
          <Navbar />
          {children}
          <Footer />
          </Session>
          </Quaryfun>
          </Tenquary>
        </div>
      </body>
    </html>
  );
}
